uapi/sched: Add missing SCHED_FLAG_ALL definition
kernel/sched/core.c:5576:23: error: use of undeclared identifier
'SCHED_FLAG_ALL'
 5576 |         kattr.sched_flags &= SCHED_FLAG_ALL;
      |                              ^

Signed-off-by: FelcoX <parbindarsingh@outlook.com>